source 'https://rubygems.org'

ruby '~> 3.2'

gem 'nats-pubsub', path: '../../../packages/ruby'
gem 'sinatra', '~> 3.1'
gem 'puma', '~> 6.4'
gem 'pg', '~> 1.5'
gem 'rake', '~> 13.1'

group :development do
  gem 'rubocop', '~> 1.59'
end
