name: Setup Ruby with Bundler
description: Install Ruby with bundler cache for the Ruby package

inputs:
  ruby-version:
    description: Ruby version to use
    required: false
    default: "3.2"
  working-directory:
    description: Working directory for bundler cache
    required: false
    default: "packages/ruby"
  install-dependencies:
    description: Run bundle install
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Set up Ruby ${{ inputs.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
        rubygems: latest

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bundle install
