# .rubocop.yml — NatsPubsub gem
# Focused for a Ruby gem: Packaging, Bundler, Rake, Performance, RSpec.

plugins:
  - rubocop-performance
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2 # match gemspec minimum to avoid false positives
  Exclude:
    - "bin/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"

# ---------- Layout & Style ----------
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*" # allow longer expectation/setup lines

Style/Documentation:
  Enabled: false # don’t force top-level docs for every class/module in a gem

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# ---------- Metrics (balanced for libs) ----------
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "Rakefile"
    - "tasks/**/*.rake"
    - "nats_pubsub.gemspec"
    - "lib/nats_pubsub/web.rb"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "lib/nats_pubsub/consumer_pool.rb"
    - "lib/nats_pubsub/consumer/message_processor.rb"

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "lib/nats_pubsub/consumer/message_processor.rb"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 150

# Optional: relax just for low-level I/O integration code
# (you can delete this once you refactor)

# ---------- Packaging / Gemspec ----------
# These ship with RuboCop core and rubocop-packaging
Gemspec/RequiredRubyVersion:
  Enabled: true # aligns with your gemspec `required_ruby_version`

Gemspec/DevelopmentDependencies:
  Enabled: true

Packaging/BundlerSetupInTests:
  Enabled: true

Packaging/RequireRelativeHardcodingLib:
  Enabled: true

# ---------- Bundler ----------
Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Bundler/GemComment:
  Enabled: false

# ---------- Performance ----------
Performance/Detect:
  Enabled: true
Performance/RedundantMerge:
  Enabled: true
Performance/FixedSize:
  Enabled: true
